# Generated by Django 4.1.1 on 2023-01-08 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_journey"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="journey",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
