# Generated by Django 4.1.1 on 2023-03-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_journey_author_alter_response_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="audio",
            field=models.FileField(blank=True, upload_to="audio/"),
        ),
    ]
