# Generated by Django 4.2.3 on 2023-10-19 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_journey_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='audio',
            field=models.FileField(blank=True, upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(['wav', 'wma', 'mp3', 'aiff', 'aac', 'm4a'])]),
        ),
        migrations.AlterField(
            model_name='journey',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'gif', 'svg', 'webp', 'png'])]),
        ),
    ]
