# Generated by Django 4.2.3 on 2023-10-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_journey_audio_alter_journey_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(help_text='Will be shown alongside entries', max_length=30, null=True, verbose_name='Nickname'),
        ),
    ]
