# Generated by Django 4.2.3 on 2023-10-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='summary',
            field=models.TextField(max_length=500),
        ),
    ]
